In [71]:
#Import Libraries
import pandas as pd
import seaborn as sns 

#Read and inspect file
df = pd.read_csv("Animal Dataset.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Animal                   205 non-null    object
 1   Height (cm)              205 non-null    object
 2   Weight (kg)              205 non-null    object
 3   Color                    205 non-null    object
 4   Lifespan (years)         205 non-null    object
 5   Diet                     205 non-null    object
 6   Habitat                  205 non-null    object
 7   Predators                205 non-null    object
 8   Average Speed (km/h)     205 non-null    object
 9   Countries Found          205 non-null    object
 10  Conservation Status      205 non-null    object
 11  Family                   205 non-null    object
 12  Gestation Period (days)  205 non-null    object
 13  Top Speed (km/h)         205 non-null    object
 14  Social Structure         205 non-null    object
 15  Offspring per Birth      205 non-null    object
dtypes: object(16)
memory usage: 25.8+ KB

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12

# DATA PREPROCESSING

Creating a function to extract numeric numbers

In [72]:
import re

def extract_numeric_average(text_value):
    # 1. If the row is empty (NaN), return None right away
    if pd.isna(text_value):
        return None
    
    try:
        # Convert to string just in case it's mixed
        text_str = str(text_value)
        
        # 2. Find all numbers (including decimals) in the text row
        # This will find ['10', '20'] out of '10-20 kg'
        numbers = re.findall(r'[-+]?\d*\.\d+|\d+', text_str)
        
        # 3. If we didn't find any numbers, return None
        if not numbers:
            return None
        
        # 4. Convert our found string numbers into actual float numbers
        float_numbers = [float(n) for n in numbers]
        
        # 5. Calculate the average of the found numbers (handles single numbers AND ranges!)
        return sum(float_numbers) / len(float_numbers)
        
    except Exception:
        # If anything weird happens, don't crash, just skip the row
        return None

In [73]:
# Clean the columns using your new function
df['Clean_Lifespan'] = df['Lifespan (years)'].apply(extract_numeric_average)
df['Clean_Gestation'] = df['Gestation Period (days)'].apply(extract_numeric_average)
df['Clean_Offspring'] = df['Offspring per Birth'].apply(extract_numeric_average)

# Check the first 5 rows to see the old columns next to your beautiful new clean ones!
df[['Lifespan (years)', 'Clean_Lifespan', 'Offspring per Birth', 'Clean_Offspring']].head()

  Lifespan (years)  Clean_Lifespan Offspring per Birth  Clean_Offspring
0            20-30            25.0                   1              1.0
1            10-12            11.0                 2-5              3.5
2            60-70            65.0                   1              1.0
3            10-14            12.0       2-4 (usually)              3.0
4            10-12            11.0               10-12             11.0

In [74]:
df['Clean_Height'] = df['Height (cm)'].apply(extract_numeric_average)
df['Clean_Weight'] = df['Weight (kg)'].apply(extract_numeric_average)
df['Clean_AvgSpeed'] = df['Average Speed (km/h)'].apply(extract_numeric_average)
df['Clean_TopSpeed'] = df['Top Speed (km/h)'].apply(extract_numeric_average)

# Let's run df.info() one more time to see our beautiful new numeric columns added!
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Animal                   205 non-null    object
 1   Height (cm)              205 non-null    object
 2   Weight (kg)              205 non-null    object
 3   Color                    205 non-null    object
 4   Lifespan (years)         205 non-null    object
 5   Diet                     205 non-null    object
 6   Habitat                  205 non-null    object
 7   Predators                205 non-null    object
 8   Average Speed (km/h)     205 non-null    object
 9   Countries Found          205 non-null    object
 10  Conservation Status      205 non-null    object
 11  Family                   205 non-null    object
 12  Gestation Period (days)  205 non-null    object
 13  Top Speed (km/h)         205 non-null    object
 14  Social Structure         205 non-null    object
 15  Offspring per Birth      205 non-null    object
 16  Clean_Lifespan           199 non-null    float64
 17  Clean_Gestation          186 non-null    float64
 18  Clean_Offspring          176 non-null    float64
 19  Clean_Height             202 non-null    float64
 20  Clean_Weight             202 non-null    float64
 21  Clean_AvgSpeed           179 non-null    float64
 22  Clean_TopSpeed           167 non-null    float64
dtypes: float64(7), object(16)
memory usage: 37.0+ KB

In [75]:
df.groupby('Conservation Status')['Clean_Weight'].mean().sort_values(ascending=False)

Conservation Status
Extinct (around 58 million years ago)    24950.000000
Extinct (around 4,000 years ago)         12000.000000
Vulnerable                                2113.128571
Least Concern                              545.918125
Near Threatened                            283.102222
Critically Endangered                      247.862281
Endangered                                 237.588182
Varies                                     166.000000
Data Deficient                             111.400000
Not Applicable                              98.280556
Not Evaluated                               75.559600
Extinct                                     25.000000
Name: Clean_Weight, dtype: float64

In [76]:
df.groupby('Habitat')['Clean_Lifespan'].mean().sort_values(ascending=False)

Habitat
Ocean Floor, Deep-sea       300.00
Islands, Coastal Areas      100.00
Coastal Waters, Seagrass     75.00
Galápagos Islands            71.25
Savannah, Forest             65.00
                             ...
Wetlands, Forests             4.00
Gardens, Grasslands           3.50
Deserts                       3.50
Varies                         NaN
Various                        NaN
Name: Clean_Lifespan, Length: 97, dtype: float64

In [77]:
df = df.drop(columns=['Clean_AvgSpeed', 'Clean_TopSpeed'])

In [78]:
print(df['Family'].unique())

['Orycteropodidae' 'Hyaenidae' 'Elephantidae' 'Felidae' 'Canidae'
 'Bovidae' 'Dendrobatidae' 'Myrmecophagidae' 'Equidae' 'Osteoglossidae'
 'Alcidae' 'Delphinidae' 'Otariidae' 'Ambystomatidae' 'Daubentoniidae'
 'Tapiridae' 'Accipitridae' 'Viverridae' 'Cercopithecidae' 'Cetorhinidae'
 'Agamidae' 'Rhinocerotidae' 'Psychrolutidae' 'Corvidae' 'Nymphalidae'
 'Balaenopteridae' 'Sulidae' 'Octopodidae' 'Hominidae' 'Ctenidae'
 'Ursidae' 'Pythonidae' 'Caviidae' 'Cryptobranchidae' 'Pomacentridae'
 'Latimeriidae' 'Chelydridae' 'Indriidae' 'Dugongidae' 'Tachyglossidae'
 'Gymnotidae' 'Spheniscidae' 'Callitrichidae' 'Erinaceidae'
 'Salamandridae' 'Pteropodidae' 'Eupleridae' 'Testudinidae' 'Phasianidae'
 'Gavialidae' 'Enteroctopodidae' 'Helodermatidae' 'Centrolenidae'
 'Mitsukurinidae' 'Lamnidae' 'Boidae' 'Cheloniidae' 'Myxinidae' 'Phocidae'
 'Hippopotamidae' 'Limulidae' 'Trochilidae' 'Indridae' 'Vespidae'
 'Strigopidae' 'Heteromyidae' 'Elapidae' 'Apterygidae' 'Varanidae'
 'Gekkonidae' 'Syngnathidae' 'Lemuridae' 'Menuridae' 'Trichechidae'
 'Stomatopoda' 'Herpestidae' 'Heterocephalidae' 'Monodontidae'
 'Nudibranchia' 'Myrmecobiidae' 'Giraffidae' 'Manidae' 'Gonodactylidae'
 'Chlamyphoridae' 'Dasypodidae' 'Ornithorhynchidae' 'Nyctibiidae'
 'Mantidae' 'Antilocapridae' 'Tetraodontidae' 'Macropodidae' 'Ailuridae'
 'Hylidae' 'Sagittariidae' 'Balaenicipitidae' 'Bradypodidae' 'Lorisidae'
 'Strigidae' 'Physeteridae' 'Atelidae' 'Cebidae' 'Talpidae' 'Tarsiidae'
 'Dasyuridae' 'Thylacinidae' 'Termitoidae' 'Ramphastidae' 'Glossinidae'
 'Rhynchocephalia' 'Pitheciidae' 'Phyllostomidae' 'Phocoenidae'
 'Odobenidae' 'Suidae' 'Rhincodontidae' 'Mustelidae' 'Vombatidae'
 'Picidae' 'Kiwaidae' 'Stegostomatidae']

In [79]:
family_to_class = {
    # --- MAMMALS ---
    'Orycteropodidae': 'Mammals', 'Hyaenidae': 'Mammals', 'Elephantidae': 'Mammals', 'Felidae': 'Mammals', 
    'Canidae': 'Mammals', 'Bovidae': 'Mammals', 'Myrmecophagidae': 'Mammals', 'Equidae': 'Mammals', 
    'Delphinidae': 'Mammals', 'Otariidae': 'Mammals', 'Daubentoniidae': 'Mammals', 'Tapiridae': 'Mammals', 
    'Viverridae': 'Mammals', 'Cercopithecidae': 'Mammals', 'Rhinocerotidae': 'Mammals', 'Balaenopteridae': 'Mammals', 
    'Hominidae': 'Mammals', 'Ursidae': 'Mammals', 'Caviidae': 'Mammals', 'Indriidae': 'Mammals', 
    'Dugongidae': 'Mammals', 'Tachyglossidae': 'Mammals', 'Callitrichidae': 'Mammals', 'Erinaceidae': 'Mammals', 
    'Pteropodidae': 'Mammals', 'Eupleridae': 'Mammals', 'Heteromyidae': 'Mammals', 'Lemuridae': 'Mammals', 
    'Trichechidae': 'Mammals', 'Herpestidae': 'Mammals', 'Heterocephalidae': 'Mammals', 'Monodontidae': 'Mammals', 
    'Myrmecobiidae': 'Mammals', 'Giraffidae': 'Mammals', 'Manidae': 'Mammals', 'Chlamyphoridae': 'Mammals', 
    'Dasypodidae': 'Mammals', 'Ornithorhynchidae': 'Mammals', 'Antilocapridae': 'Mammals', 'Macropodidae': 'Mammals', 
    'Ailuridae': 'Mammals', 'Bradypodidae': 'Mammals', 'Lorisidae': 'Mammals', 'Physeteridae': 'Mammals', 
    'Atelidae': 'Mammals', 'Cebidae': 'Mammals', 'Talpidae': 'Mammals', 'Tarsiidae': 'Mammals', 
    'Dasyuridae': 'Mammals', 'Thylacinidae': 'Mammals', 'Pitheciidae': 'Mammals', 'Phyllostomidae': 'Mammals', 
    'Phocoenidae': 'Mammals', 'Odobenidae': 'Mammals', 'Suidae': 'Mammals', 'Mustelidae': 'Mammals', 
    'Vombatidae': 'Mammals', 'Phocidae': 'Mammals', 'Hippopotamidae': 'Mammals', 'Indridae': 'Mammals',

    # --- BIRDS ---
    'Alcidae': 'Birds', 'Accipitridae': 'Birds', 'Corvidae': 'Birds', 'Sulidae': 'Birds', 
    'Spheniscidae': 'Birds', 'Phasianidae': 'Birds', 'Trochilidae': 'Birds', 'Apterygidae': 'Birds', 
    'Menuridae': 'Birds', 'Nyctibiidae': 'Birds', 'Sagittariidae': 'Birds', 'Balaenicipitidae': 'Birds', 
    'Strigidae': 'Birds', 'Ramphastidae': 'Birds', 'Picidae': 'Birds', 'Strigopidae': 'Birds',

    # --- REPTILES ---
    'Colubridae': 'Reptiles', 'Boidae': 'Reptiles', 'Crocodylidae': 'Reptiles', 
    'Testudinidae': 'Reptiles', 'Elapidae': 'Reptiles', 'Viperidae': 'Reptiles',
    'Agamidae': 'Reptiles', 'Pythonidae': 'Reptiles', 'Chelydridae': 'Reptiles', 
    'Gavialidae': 'Reptiles', 'Helodermatidae': 'Reptiles', 'Cheloniidae': 'Reptiles', 
    'Varanidae': 'Reptiles', 'Gekkonidae': 'Reptiles', 'Rhynchocephalia': 'Reptiles',
    
    # --- AMPHIBIANS ---
    'Ranidae': 'Amphibians', 'Bufonidae': 'Amphibians', 'Hylidae': 'Amphibians', 
    'Salamandridae': 'Amphibians', 'Dendrobatidae': 'Amphibians',
    'Ambystomatidae': 'Amphibians', 'Cryptobranchidae': 'Amphibians', 'Centrolenidae': 'Amphibians',

    # --- FISH ---
    'Osteoglossidae': 'Fish', 'Cetorhinidae': 'Fish', 'Psychrolutidae': 'Fish', 'Pomacentridae': 'Fish', 
    'Latimeriidae': 'Fish', 'Mitsukurinidae': 'Fish', 'Lamnidae': 'Fish', 'Myxinidae': 'Fish', 
    'Syngnathidae': 'Fish', 'Tetraodontidae': 'Fish', 'Rhincodontidae': 'Fish', 'Stegostomatidae': 'Fish', 
    'Gymnotidae': 'Fish',

    # --- INVERTEBRATES ---
    'Nymphalidae': 'Invertebrates', 'Octopodidae': 'Invertebrates', 'Ctenidae': 'Invertebrates', 
    'Enteroctopodidae': 'Invertebrates', 'Limulidae': 'Invertebrates', 'Vespidae': 'Invertebrates', 
    'Stomatopoda': 'Invertebrates', 'Nudibranchia': 'Invertebrates', 'Gonodactylidae': 'Invertebrates', 
    'Mantidae': 'Invertebrates', 'Termitoidae': 'Invertebrates', 'Glossinidae': 'Invertebrates', 
    'Kiwaidae': 'Invertebrates'
}

# Apply mapping and overwrite database
df['Animal_Class'] = df['Family'].map(family_to_class).fillna('Other')

In [80]:
# Remove any row where the exact same animal name is repeated
df = df.drop_duplicates(subset=['Animal'], keep='first')

In [81]:
import numpy as np

# Clear out any duplicate animal entries right off the bat
df = df.drop_duplicates(subset=['Animal'], keep='first')

# Spot-fixing the Arabian Oryx so it routes right to Asia instead of falling into 'Other'
df.loc[df['Animal'] == 'Arabian Oryx', 'Continent'] = 'Asia'

# Set up marine keywords to help catch global ocean species down the line
marine_classes = ['Fish', 'Invertebrates', 'Reptiles', 'Amphibians']
marine_animals = ['Whale', 'Dolphin', 'Shark', 'Turtle', 'Shrimp', 'Nudibranch']

# Grouping text keywords into continent buckets based on what we saw in the data
conditions = [
    # Rule 1: Catching ocean generalists and specific marine zones
    ((df['Countries Found'].str.contains('Worldwide|Ocean', case=False, na=False)) & 
     ((df['Animal_Class'].isin(marine_classes)) | (df['Animal'].str.contains('|'.join(marine_animals), case=False, na=False)))) |
    df['Countries Found'].str.contains('Pacific|Atlantic|Indo-Pacific|Galapagos|GalÃ¡pagos|Galápagos|Arctic', case=False, na=False),
    
    # Rule 2: Europe
    df['Countries Found'].str.contains('Europe|Alps|Spain|Portugal', case=False, na=False),
    
    # Rule 3: Asia
    df['Countries Found'].str.contains('Asia|Sumatra|Borneo|India|China|Russia|Siberia|Southeast|Indonesia|Malaysia|Vietnam|Laos', case=False, na=False),
    
    # Rule 4: Africa
    df['Countries Found'].str.contains('Africa|Madagascar|Congo|Central Africa', case=False, na=False),
    
    # Rule 5: Americas
    df['Countries Found'].str.contains('America|Brazil|Mexico|Amazon|Colombia|Argentina|Chile|Alaska', case=False, na=False),
    
    # Rule 6: Oceania
    df['Countries Found'].str.contains('New Zealand|Australia|Papua New Guinea|Oceania', case=False, na=False),
    
    # Rule 7: Antarctica
    df['Countries Found'].str.contains('Antarctica', case=False, na=False),
    
    # Rule 8: Global land generalists (like dogs or woodpeckers)
    df['Countries Found'].str.contains('Worldwide|Northern Hemisphere', case=False, na=False)
]

# Text tags that map directly to the condition blocks above
continent_choices = [
    'Ocean',
    'Europe',
    'Asia',
    'Africa',
    'Americas',
    'Oceania',
    'Antarctica',
    'Worldwide (Terrestrial)'
]

# 4. Map the choices
continent_choices = ['Ocean', 'Europe', 'Asia', 'Africa', 'Americas', 'Oceania', 'Antarctica', 'Worldwide (Terrestrial)']
df['Continent'] = np.select(conditions, continent_choices, default='Other')

# 5. RUN THIS LAST so it overrides the 'Other' result perfectly!
df.loc[df['Animal'] == 'Arabian Oryx', 'Continent'] = 'Asia'

# 6. Drop 'Countries Found' now that we are done
if 'Countries Found' in df.columns:
    df = df.drop(columns=['Countries Found'])

# Verify that 'Other' is now 0 and 'Asia' increases to 46
print(df['Continent'].value_counts())

Continent
Asia                       46
Ocean                      41
Americas                   39
Africa                     37
Oceania                    20
Europe                      7
Worldwide (Terrestrial)     6
Name: count, dtype: int64

In [84]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

# Load secrets from the .env file
load_dotenv()

USERNAME = "root"
PASSWORD = os.getenv("DB_PASSWORD")  # <-- Reads cleanly from your hidden file!
HOST = "127.0.0.1"
PORT = "3306"
DATABASE = "Animal_Dataset_Conservation"

engine = create_engine(
    f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)
df.to_sql(name="animal_clean_records", con=engine, if_exists="replace", index=False)

196